services:
  minio:
    image: minio/minio:latest
    container_name: airflow_minio1
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - minio_data:/data
    networks:
      - airflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  mc:
    image: minio/mc:latest
    container_name: airflow_minio_mc1
    depends_on:
      - minio
    networks:
      - airflow
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "mc alias set local http://minio:9000 minio minio12345 &&
       mc mb -p local/orders &&
       mc policy set public local/orders || true &&
       sleep infinity"

volumes:
  minio_data:

networks:
  airflow:
    external: true