create table airflow.customers (
  id INT64,
  first_name STRING,
  last_name STRING,
  email STRING,
  gender STRING,
  phone STRING,
  country STRING,
  city STRING,
  birthday STRING,
  company STRING,
  department_comp STRING,
  job STRING
);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (1, 'Fayth', 'Tosspell', 'ftosspell0@ucsd.edu', 'Female', '202-521-8579', 'United States', 'Washington', '8/2/1981', 'Jacobson and Sons', 'Engineering', 'Web Developer I');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (2, 'Augustina', 'Sheerin', 'asheerin1@yelp.com', 'Female', '448-661-9426', 'France', 'Paris 14', '3/18/1981', null, '', 'Legal Assistant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (3, 'Sibylla', 'Rubenovic', 'srubenovic2@blinklist.com', 'Female', '347-264-5132', 'Spain', 'Palma De Mallorca', '7/11/1979', 'Metz Inc', 'Research and Development', 'Budget/Accounting Analyst III');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (4, 'Shantee', 'Onion', 'sonion3@tinyurl.com', 'Genderqueer', '427-528-3437', 'China', 'Dongyu', '9/6/1992', 'Kuvalis LLC', 'Sales', 'Structural Analysis Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (5, 'Ricca', 'Brauninger', 'rbrauninger4@mayoclinic.com', 'Polygender', '117-275-4303', 'China', 'Xue’an', '12/17/1966', 'Fadel, Blanda and Hermiston', 'Research and Development', 'Product Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (6, 'Mozes', 'Ludlem', 'mludlem5@hud.gov', 'Non-binary', '674-680-6991', 'Portugal', 'Vale Covo', '2/6/1962', 'Hahn, Lebsack and Graham', 'Accounting', 'Media Manager II');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (7, 'Barry', 'Jenken', 'bjenken6@nifty.com', 'Male', '750-475-4744', 'Ghana', 'Keta', '6/21/1962', null, '', 'Marketing Assistant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (8, 'Rolf', 'Eltun', 'reltun7@devhub.com', 'Male', '111-760-2850', 'Thailand', 'Chum Phae', '3/13/1969', 'Auer, Crooks and Fadel', 'Legal', 'Business Systems Development Analyst');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (9, 'Minor', 'Broggetti', 'mbroggetti8@symantec.com', 'Male', '281-602-5113', 'Serbia', 'Radojevo', '4/6/1990', null, '', 'Automation Specialist II');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (10, 'Edan', 'Kikke', 'ekikke9@quantcast.com', 'Male', null, 'Philippines', 'Pangantocan', '11/18/1971', 'Grimes LLC', 'Training', 'Clinical Specialist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (11, 'Matelda', 'Lucken', 'mluckena@forbes.com', 'Genderqueer', '492-245-7185', 'China', 'Lhasa', '6/10/1964', 'Boehm, Schultz and Mayer', 'Training', 'Structural Analysis Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (12, 'Randy', 'Vicent', 'rvicentb@webmd.com', 'Agender', '163-456-8471', 'Kazakhstan', 'Shu', '2/27/1979', null, '', 'Technical Writer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (13, 'Millie', 'Cescon', 'mcesconc@elpais.com', 'Female', '430-270-8978', 'Norway', 'Mosjøen', '2/3/1987', 'Block-Simonis', 'Marketing', 'Information Systems Manager');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (14, 'Johnathon', 'McOwan', 'jmcowand@answers.com', 'Genderqueer', '603-821-7899', 'Russia', 'Vershino-Shakhtaminskiy', '1/13/1977', 'Simonis Group', 'Product Management', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (15, 'Janelle', 'Billany', 'jbillanye@washington.edu', 'Female', '284-687-1289', 'China', 'Dongjiao', '3/5/1983', 'Kozey-Cronin', 'Product Management', 'Developer II');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (16, 'Russ', 'Kabisch', 'rkabischf@e-recht24.de', 'Male', '616-895-2548', 'Canada', 'Ferme-Neuve', '12/14/1982', 'Leuschke-Cummerata', 'Product Management', 'Legal Assistant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (17, 'Jessica', 'Staynes', 'jstaynesg@prlog.org', 'Female', '352-378-3924', 'China', 'Dayou', '6/2/1982', null, '', 'Dental Hygienist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (18, 'Humfrey', 'Castel', 'hcastelh@canalblog.com', 'Male', '207-723-6101', 'Portugal', 'São Miguel do Rio Torto', '11/17/1993', null, '', 'Electrical Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (19, 'Audre', 'Knell', 'aknelli@behance.net', 'Female', '404-372-4199', 'Cape Verde', 'Cova Figueira', '5/23/1999', 'Braun, Schuster and Rau', 'Human Resources', 'General Manager');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (20, 'Karleen', 'Milmo', 'kmilmoj@springer.com', 'Female', '902-565-6795', 'China', 'Tashang', '8/12/1969', 'Stroman, McCullough and Lebsack', 'Engineering', 'Mechanical Systems Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (21, 'Arleen', 'Obeney', 'aobeneyk@wikipedia.org', 'Female', '460-271-5307', 'China', 'Xiamao', '12/13/2001', 'Rutherford, Stark and Gottlieb', 'Human Resources', 'Junior Executive');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (22, 'Delores', 'Sivyour', 'dsivyourl@discuz.net', 'Genderfluid', null, 'Philippines', 'Tulay na Lupa', '10/22/1972', 'Dicki-Donnelly', 'Legal', 'Associate Professor');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (23, 'Conrado', 'Brandli', 'cbrandlim@google.fr', 'Male', '441-700-8447', 'China', 'Xiaolou', '10/7/1995', 'Heller, Wolff and Koch', 'Sales', 'Software Consultant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (24, 'Des', 'Tinwell', 'dtinwelln@intel.com', 'Male', '423-426-7876', 'China', 'Zonghan', '1/3/1964', 'McKenzie, Steuber and Quigley', 'Human Resources', 'Editor');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (25, 'Teddy', 'Elvy', 'telvyo@msn.com', 'Female', '881-577-6977', 'Indonesia', 'Binjai', '11/18/1991', 'Murray LLC', 'Accounting', 'Nurse Practicioner');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (26, 'Tim', 'Karlsson', null, 'Male', '857-167-5859', 'Finland', 'Kuusjoki', '8/21/1979', 'Jones, Gibson and Bernhard', 'Training', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (27, 'Jorrie', 'Di Matteo', 'jdimatteoq@stanford.edu', 'Female', '273-434-9044', 'Indonesia', 'Amagarapati', '2/12/1970', null, '', 'Computer Systems Analyst I');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (28, 'Hebert', 'Shayler', 'hshaylerr@amazonaws.com', 'Male', '641-500-7631', 'China', 'Qidi', '9/20/1996', 'Leffler LLC', 'Product Management', 'Paralegal');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (29, 'Duff', 'Licciardello', 'dlicciardellos@flavors.me', 'Male', '363-917-4294', 'Indonesia', 'Kediren', '1/23/1995', null, '', 'Product Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (30, 'Paco', 'Sisland', 'psislandt@independent.co.uk', 'Genderfluid', null, 'China', 'Sanchahe', '9/24/1993', 'Schmeler, Witting and Schuster', 'Services', 'Software Consultant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (31, 'Jany', 'Sposito', null, 'Female', '673-581-7288', 'Ecuador', 'Cuenca', '2/14/2004', 'Beahan, Kuhlman and Adams', 'Legal', 'VP Accounting');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (32, 'Stephanus', 'Exer', 'sexerv@un.org', 'Male', '737-494-8830', 'Mexico', 'Benito Juarez', '12/19/1965', 'Zieme-Veum', 'Marketing', 'Systems Administrator III');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (33, 'Louisa', 'Musgrave', null, 'Female', '101-417-0582', 'Brazil', 'Chapadinha', '11/20/1987', 'Hoppe Inc', 'Human Resources', 'Accounting Assistant IV');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (34, 'Darleen', 'Adnams', 'dadnamsx@mediafire.com', 'Female', '624-212-5890', 'Russia', 'Drakino', '9/1/1995', 'Crist Inc', 'Human Resources', 'Account Executive');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (35, 'Adrienne', 'Skym', 'askymy@alibaba.com', 'Female', '258-632-4365', 'China', 'Baoxu', '4/24/1961', 'Barrows and Sons', 'Training', 'Pharmacist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (36, 'Mella', 'Suermeier', 'msuermeierz@timesonline.co.uk', 'Female', '620-607-3956', 'Indonesia', 'Kakaek', '3/28/1961', 'Schaden Group', 'Support', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (37, 'Inna', 'Biggans', 'ibiggans10@webmd.com', 'Polygender', '249-933-7924', 'Azerbaijan', 'Qazax', '8/31/1982', 'Schumm, Denesik and Braun', 'Product Management', 'Recruiter');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (38, 'Elga', 'Bruford', 'ebruford11@hhs.gov', 'Female', '863-733-2194', 'Philippines', 'Conner', '9/28/1963', null, '', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (39, 'Anna-maria', 'Backen', 'abacken12@123-reg.co.uk', 'Female', '714-439-7792', 'China', 'Yihe', '2/8/2001', null, '', 'Sales Representative');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (40, 'Bartholomeo', 'Towner', 'btowner13@columbia.edu', 'Male', '793-550-2109', 'Ukraine', 'Chulakivka', '1/12/1965', 'Medhurst, Nicolas and Toy', 'Marketing', 'Environmental Specialist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (41, 'Kristo', 'Dalloway', 'kdalloway14@list-manage.com', 'Male', '801-504-5348', 'China', 'Huangbu', '10/31/2000', null, '', 'Computer Systems Analyst II');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (42, 'Kimberlyn', 'Gentil', 'kgentil15@tripod.com', 'Agender', '276-209-0110', 'Philippines', 'Villaviciosa', '3/28/1999', 'Stamm-Heidenreich', 'Support', 'Senior Financial Analyst');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (43, 'Deedee', 'Jedrysik', 'djedrysik16@github.com', 'Female', '737-823-5120', 'Canada', 'Leduc', '11/15/1999', 'Kertzmann, Kihn and Nader', 'Research and Development', 'Actuary');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (44, 'Gearard', 'Ruegg', 'gruegg17@biblegateway.com', 'Male', '850-134-0655', 'United States', 'Tallahassee', '6/19/1988', 'Shanahan-Glover', 'Research and Development', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (45, 'Quinn', 'Belchambers', 'qbelchambers18@dion.ne.jp', 'Male', '964-843-9738', 'Czech Republic', 'Zbůch', '3/2/1972', 'Ratke-Hansen', 'Legal', 'VP Product Management');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (46, 'Dinny', 'Andreacci', 'dandreacci19@furl.net', 'Female', '434-469-8466', 'Netherlands', 'Eindhoven', '10/4/1997', 'Jacobi LLC', 'Engineering', 'Operator');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (47, 'Gannon', 'Laux', 'glaux1a@wunderground.com', 'Male', '274-395-1665', 'China', 'Handegate', '4/5/1972', 'Hyatt Inc', 'Engineering', 'VP Accounting');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (48, 'Parsifal', 'St. Aubyn', 'pstaubyn1b@fda.gov', 'Male', '176-502-5429', 'Colombia', 'Aipe', '10/15/1993', 'Schamberger-Swaniawski', 'Marketing', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (49, 'Wolfgang', 'Morando', 'wmorando1c@lulu.com', 'Male', '392-660-6415', 'Colombia', 'Bogotá', '11/29/1969', 'Hegmann Inc', 'Marketing', 'Human Resources Manager');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (50, 'Guenevere', 'Proppers', 'gproppers1d@domainmarket.com', 'Female', '903-491-5738', 'Czech Republic', 'Velká Bíteš', '11/2/1989', 'Botsford, Hills and Crona', 'Human Resources', 'Administrative Officer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (51, 'Augustine', 'Callender', 'acallender1e@dell.com', 'Male', '868-678-6646', 'Brazil', 'Marília', '11/5/1995', 'Boyer-Rath', 'Services', 'Food Chemist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (52, 'Ricard', 'Jardein', 'rjardein1f@devhub.com', 'Bigender', '812-639-2423', 'Indonesia', 'Singkup', '9/11/2003', 'Bauch-Prosacco', 'Human Resources', 'Sales Associate');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (53, 'Shaw', 'Cristofaro', 'scristofaro1g@sohu.com', 'Male', '559-140-0214', 'Philippines', 'Tilik', '9/12/1966', 'Schmidt-Deckow', 'Services', 'VP Marketing');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (54, 'Neala', 'Caulder', 'ncaulder1h@sogou.com', 'Female', '165-452-3336', 'China', 'Keli', '5/16/1998', 'Hilll Inc', 'Legal', 'Senior Quality Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (55, 'Glennis', 'Laverock', null, 'Female', null, 'Indonesia', 'Krajan', '3/29/1984', 'Hegmann-MacGyver', 'Marketing', 'Physical Therapy Assistant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (56, 'Carmella', 'Ascrofte', 'cascrofte1j@wix.com', 'Female', '605-162-4462', 'Indonesia', 'Sekararum', '5/26/1980', 'Kovacek, King and Schmitt', 'Research and Development', 'Sales Associate');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (57, 'Rudolf', 'Salandino', 'rsalandino1k@unc.edu', 'Male', '605-594-6690', 'Kenya', 'Kericho', '7/28/1979', 'Hilll-Gutmann', 'Support', 'Graphic Designer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (58, 'Griff', 'Charles', 'gcharles1l@purevolume.com', 'Male', '685-963-9151', 'Indonesia', 'Sukaharja', '6/3/1992', 'Corwin, Mertz and Toy', 'Sales', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (59, 'Krystle', 'Nason', null, 'Female', '101-266-4712', 'France', 'Saint-Brieuc', '8/21/1991', 'Luettgen-Lang', 'Marketing', 'VP Quality Control');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (60, 'Burnaby', 'Whiteland', 'bwhiteland1n@example.com', 'Male', '863-113-6373', 'Poland', 'Kamieniec Wrocławski', '5/31/2000', null, '', 'Senior Cost Accountant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (61, 'Clerissa', 'Surpliss', 'csurpliss1o@sogou.com', 'Polygender', '321-365-4838', 'Dominican Republic', 'Sabana Grande de Palenque', '11/7/1962', 'Streich Inc', 'Accounting', 'Marketing Assistant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (62, 'Bell', 'Klimentyev', 'bklimentyev1p@jalbum.net', 'Female', '793-980-2922', 'Indonesia', 'Nusajaya', '5/16/1990', 'Jacobson, Mann and Monahan', 'Product Management', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (63, 'Thorsten', 'Brodway', 'tbrodway1q@instagram.com', 'Male', '303-497-1402', 'Philippines', 'Taltal', '11/1/1986', null, '', 'Research Nurse');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (64, 'Mamie', 'Hugk', 'mhugk1r@disqus.com', 'Female', '128-498-8725', 'France', 'Courtaboeuf', '8/24/1996', 'Rau-Conroy', 'Business Development', 'Nuclear Power Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (65, 'Ewart', 'Figgen', 'efiggen1s@feedburner.com', 'Male', '645-429-9179', 'China', 'Bozhou', '11/7/1966', 'Lueilwitz LLC', 'Human Resources', 'Editor');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (66, 'Andy', 'Heister', 'aheister1t@craigslist.org', 'Male', '709-708-8751', 'El Salvador', 'Ciudad Arce', '11/3/2003', 'Will-Ryan', 'Engineering', 'Marketing Assistant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (67, 'Donnie', 'Leach', 'dleach1u@comcast.net', 'Female', '515-849-3986', 'South Africa', 'Boshof', '9/17/2002', 'Luettgen-Sipes', 'Product Management', 'Nuclear Power Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (68, 'Anjanette', 'Rotham', 'arotham1v@cnet.com', 'Female', '766-964-2558', 'Mexico', 'Buenavista', '5/1/1987', 'Williamson, Goldner and Dietrich', 'Marketing', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (69, 'Lacie', 'Gianilli', 'lgianilli1w@army.mil', 'Female', '876-308-6819', 'Portugal', 'Lameira', '10/30/1998', 'Shanahan-Haley', 'Accounting', 'Paralegal');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (70, 'Linette', 'Kinmond', 'lkinmond1x@example.com', 'Female', '116-191-8883', 'Sweden', 'Norrtälje', '9/7/2000', 'Smitham-Goyette', 'Support', 'Senior Sales Associate');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (71, 'Amil', 'Leafe', 'aleafe1y@diigo.com', 'Female', '271-635-2022', 'Portugal', 'Praia da Barra', '6/7/2002', null, '', 'Assistant Manager');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (72, 'Granville', 'Bowshire', 'gbowshire1z@example.com', 'Male', null, 'United States', 'Tucson', '10/5/1966', 'Mante-Parisian', 'Research and Development', 'Business Systems Development Analyst');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (73, 'Berri', 'Spohrmann', 'bspohrmann20@gnu.org', 'Female', '763-184-1356', 'Philippines', 'San Miguel', '1/4/2002', 'Koepp-Lehner', 'Research and Development', 'Safety Technician I');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (74, 'Ax', 'Vian', 'avian21@patch.com', 'Male', '741-845-8974', 'Philippines', 'Bacnar', '1/10/2005', null, '', 'Senior Cost Accountant');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (75, 'Ermina', 'Crocket', 'ecrocket22@nationalgeographic.com', 'Female', '637-441-6154', 'Botswana', 'Letlhakeng', '11/7/1968', 'Trantow Inc', 'Sales', 'VP Quality Control');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (76, 'Ruttger', 'Gwioneth', 'rgwioneth23@bbb.org', 'Male', '622-420-6947', 'Finland', 'Kittilä', '8/16/1985', 'Wilderman, Zulauf and Reilly', 'Research and Development', 'Accountant III');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (77, 'Matteo', 'Breffit', 'mbreffit24@reverbnation.com', 'Male', '530-363-0808', 'Morocco', 'Souq Larb’a al Gharb', '1/29/1969', 'Shanahan LLC', 'Support', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (78, 'Alexandro', 'Tenpenny', 'atenpenny25@cpanel.net', 'Male', '158-728-3078', 'Brazil', 'Paraty', '9/7/1987', 'McGlynn-Streich', 'Engineering', 'Geologist I');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (79, 'Paule', 'Rossborough', 'prossborough26@theguardian.com', 'Female', '337-296-3953', 'Bangladesh', 'Mathba', '8/4/1997', 'Considine, Cruickshank and Considine', 'Business Development', 'Senior Editor');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (80, 'Leta', 'Mayhou', 'lmayhou27@sitemeter.com', 'Female', '407-381-0771', 'Poland', 'Krzemienica', '7/1/1962', 'Hartmann, Kling and Abernathy', 'Services', 'Assistant Professor');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (81, 'Peirce', 'Seatter', 'pseatter28@google.com', 'Male', '352-279-2608', 'Russia', 'Leonidovo', '1/31/1975', 'Stehr-Mosciski', 'Training', 'Nurse');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (82, 'Riannon', 'Bunn', 'rbunn29@foxnews.com', 'Female', '981-690-7077', 'China', 'Xinghai', '5/11/1967', 'Mayert, Moore and Terry', 'Services', 'Sales Representative');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (83, 'Mehetabel', 'Dibsdale', null, 'Female', '956-416-3244', 'Azerbaijan', 'Altıağac', '11/16/2001', 'Muller-Armstrong', 'Support', 'Graphic Designer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (84, 'Vanni', 'Gledhall', 'vgledhall2b@imdb.com', 'Female', '782-887-7348', 'Uruguay', 'Colonia Nicolich', '3/28/1970', 'Schaden Group', 'Accounting', 'Professor');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (85, 'Adoree', 'MacKay', 'amackay2c@pbs.org', 'Female', '751-741-3588', 'Indonesia', 'Padaan', '6/3/1968', 'Swaniawski Inc', 'Marketing', 'Design Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (86, 'Sergent', 'Prattington', 'sprattington2d@woothemes.com', 'Male', '182-126-5078', 'China', 'Tongzilin', '11/23/1994', 'Paucek, Weber and Berge', 'Sales', 'Electrical Engineer');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (87, 'Morly', 'Belch', 'mbelch2e@stumbleupon.com', 'Male', '843-361-8658', 'Peru', 'Pampachiri', '3/13/1981', null, '', 'Community Outreach Specialist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (88, 'Renate', 'Cady', 'rcady2f@wunderground.com', 'Female', '576-114-7225', 'Indonesia', 'Sumber Tengah', '9/9/1986', 'Walter-Rodriguez', 'Accounting', 'Recruiter');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (89, 'Humbert', 'Dolden', 'hdolden2g@wikia.com', 'Male', '956-124-2638', 'Philippines', 'Canturay', '3/20/1977', 'Jast-Morar', 'Research and Development', 'Web Developer I');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (90, 'Sidonnie', 'Loney', 'sloney2h@lycos.com', 'Female', '263-518-5580', 'Canada', 'Varennes', '2/28/1968', 'Trantow, Dare and Gusikowski', 'Human Resources', 'Staff Scientist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (91, 'Katha', 'Bowmaker', 'kbowmaker2i@dedecms.com', 'Female', '953-625-7644', 'Afghanistan', 'Gardēz', '3/7/1991', null, '', 'Teacher');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (92, 'Mark', 'Sussex', 'msussex2j@altervista.org', 'Male', '382-212-3360', 'Vietnam', 'Tân An', '1/7/2001', 'Schmitt, Conroy and Predovic', 'Training', 'Account Coordinator');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (93, 'Corbin', 'Jaszczak', 'cjaszczak2k@bing.com', 'Male', '906-101-7183', 'Czech Republic', 'Sobotín', '1/14/2005', null, '', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (94, 'Stanfield', 'Dickie', 'sdickie2l@abc.net.au', 'Male', '506-424-9303', 'Paraguay', 'Eusebio Ayala', '12/31/1990', 'Carroll, Donnelly and Feest', 'Legal', null);
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (95, 'Peri', 'Scullin', 'pscullin2m@hibu.com', 'Female', '756-572-5300', 'Poland', 'Golcowa', '11/4/1963', 'Wolf LLC', 'Services', 'Clinical Specialist');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (96, 'Salem', 'Parfett', 'sparfett2n@qq.com', 'Male', '231-494-8003', 'Russia', 'Grazhdanskoye', '8/26/1989', 'Brakus, Crona and Reinger', 'Support', 'Environmental Tech');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (97, 'Wye', 'Rycroft', 'wrycroft2o@dell.com', 'Male', '294-140-6205', 'Syria', 'Tallbīsah', '2/8/1998', null, '', 'Research Nurse');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (98, 'Christian', 'Switzer', 'cswitzer2p@ebay.co.uk', 'Male', '240-272-3974', 'Portugal', 'Carregado', '1/4/1978', 'Oberbrunner, Kozey and Cremin', 'Sales', 'Data Coordinator');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (99, 'Matty', 'Costi', 'mcosti2q@rambler.ru', 'Male', '508-273-6842', 'Brazil', 'Pitangui', '5/9/1972', 'Lubowitz and Sons', 'Support', 'VP Sales');
insert into airflow.customers (id, first_name, last_name, email, gender, phone, country, city, birthday, company, department_comp, job) values (100, 'Skipp', 'Jakubczyk', 'sjakubczyk2r@paypal.com', 'Male', '590-151-8523', 'Tajikistan', 'Abdurahmoni Jomí', '5/16/1974', 'Ullrich, Graham and Anderson', 'Legal', null);
